<?php

declare(strict_types=1);

return [
    'global_role_codes' => ['administrator', 'general_manager'],

    'abilities' => [
        'platform.view' => ['administrator', 'general_manager'],
        'inbox.view' => ['administrator', 'general_manager', 'branch_manager'],
        'users.manage' => ['administrator'],
        'staff.view' => ['general_manager', 'branch_manager'],
        'staff.manage' => ['general_manager', 'branch_manager'],
        'branches.view' => ['administrator', 'general_manager', 'branch_manager', 'coordinator', 'verifier', 'cashier'],
        'branches.manage' => ['general_manager'],
        'branch-settings.view' => ['administrator', 'general_manager', 'branch_manager'],
        'branch-settings.manage' => ['general_manager', 'branch_manager'],
        'products.view' => ['administrator', 'general_manager', 'branch_manager', 'distributor'],
        'products.manage' => ['general_manager', 'branch_manager'],
        'categories.view' => ['administrator', 'general_manager', 'branch_manager', 'coordinator'],
        'categories.manage' => ['general_manager', 'branch_manager'],
        'point-settings.view' => ['administrator', 'general_manager', 'branch_manager'],
        'point-settings.manage' => ['general_manager'],
        'applications.view' => ['administrator', 'general_manager', 'branch_manager', 'coordinator', 'verifier'],
        'applications.create' => ['coordinator'],
        'applications.assign-verifier' => ['coordinator'],
        'applications.verify' => ['verifier'],
        'applications.decide' => ['general_manager', 'branch_manager'],
        'distributors.manage' => ['general_manager'],
        'credit-accounts.open' => ['general_manager', 'branch_manager'],
        'credit-limits.increase' => ['general_manager'],
        'voucher-plans.manage' => ['general_manager'],
        'vouchers.view' => ['administrator', 'general_manager', 'branch_manager', 'coordinator', 'cashier', 'distributor'],
        'vouchers.pre-issue' => ['distributor'],
        'vouchers.approve' => ['coordinator', 'branch_manager', 'general_manager'],
        'vouchers.disburse' => ['cashier', 'branch_manager', 'general_manager'],
        'customers.view' => ['administrator', 'general_manager', 'branch_manager', 'coordinator', 'cashier', 'distributor'],
        'customers.create' => ['distributor'],
        'customers.manage' => ['general_manager', 'branch_manager'],
        'customers.update.request' => ['cashier'],
        'customers.update.approve' => ['branch_manager', 'general_manager'],
        'customers.verify' => ['cashier'],
        'customers.transfer.view' => ['administrator', 'general_manager', 'branch_manager', 'coordinator', 'distributor'],
        'customers.transfer.request' => ['distributor'],
        'customers.transfer.decide' => ['coordinator', 'general_manager'],
        'customers.transfer.cancel' => ['distributor'],
        'reconciliations.manual' => ['cashier', 'general_manager'],
        'credit-increase.view' => ['administrator', 'general_manager', 'branch_manager', 'coordinator', 'distributor'],
        'credit-increase.request' => ['distributor', 'coordinator'],
        'credit-increase.pre-authorize' => ['coordinator', 'branch_manager', 'general_manager'],
        'credit-increase.decide' => ['branch_manager', 'general_manager'],
        'payments.view' => ['administrator', 'general_manager', 'branch_manager', 'coordinator', 'distributor'],
        'payments.create' => ['cashier', 'branch_manager', 'general_manager'],
        'payments.reverse' => ['cashier', 'branch_manager', 'general_manager'],
        'cutoffs.view' => ['administrator', 'general_manager', 'branch_manager', 'coordinator', 'distributor'],
        'cutoffs.manage' => ['branch_manager', 'general_manager'],
        'reconciliations.import' => ['cashier', 'general_manager'],
        'reconciliations.view' => ['administrator', 'general_manager', 'branch_manager', 'coordinator'],
        'reconciliations.verify' => ['branch_manager', 'general_manager'],
        'points.view' => ['administrator', 'general_manager', 'branch_manager', 'coordinator', 'distributor'],
        'points.redeem.request' => ['distributor'],
        'points.redeem.decide' => ['branch_manager', 'general_manager'],
        'points.category' => ['branch_manager', 'general_manager'],
    ],
];
